In [1]:
from RUL_part import *

In [16]:
#initial
set_seed(612)
w_k=np.random.rand(6,1)
pi_k=np.random.random(size=None)
mu_mk=np.random.rand(3,1)
Sigma_mk=generate_rand_psd(3)
sigma_mk_2=np.random.random(size=None)


set_seed(1190)
w_j=np.random.rand(6,1)
pi_j=np.random.random(size=None)
# mu_mj=np.random.rand(3,1)
mu_mj = np.zeros((3,1))
# Sigma_mj=generate_rand_psd(3)
Sigma_mj = np.identity(3)/100
sigma_mj_2=np.random.random(size=None)

args_a = [[pi_k,w_k,[mu_mk,Sigma_mk,sigma_mk_2],
                               [mu_mk,Sigma_mk,sigma_mk_2],[mu_mk,Sigma_mk,sigma_mk_2],[mu_mk,Sigma_mk,sigma_mk_2],
                              [mu_mk,Sigma_mk,sigma_mk_2],[mu_mk,Sigma_mk,sigma_mk_2],[mu_mk,Sigma_mk,sigma_mk_2]]]
args_b = [[pi_j,w_j,[mu_mj,Sigma_mj,sigma_mj_2],
                               [mu_mj,Sigma_mj,sigma_mj_2],[mu_mj,Sigma_mj,sigma_mj_2],[mu_mj,Sigma_mj,sigma_mj_2],
                              [mu_mj,Sigma_mj,sigma_mj_2],[mu_mj,Sigma_mj,sigma_mj_2],[mu_mj,Sigma_mj,sigma_mj_2]]]


args = [[pi_k,w_k,[mu_mk,Sigma_mk,sigma_mk_2],
                               [mu_mk,Sigma_mk,sigma_mk_2],[mu_mk,Sigma_mk,sigma_mk_2],[mu_mk,Sigma_mk,sigma_mk_2],
                              [mu_mk,Sigma_mk,sigma_mk_2],[mu_mk,Sigma_mk,sigma_mk_2],[mu_mk,Sigma_mk,sigma_mk_2]],
                                 [pi_j,w_j,[mu_mj,Sigma_mj,sigma_mj_2],
                               [mu_mj,Sigma_mj,sigma_mj_2],[mu_mj,Sigma_mj,sigma_mj_2],[mu_mj,Sigma_mj,sigma_mj_2],
                              [mu_mj,Sigma_mj,sigma_mj_2],[mu_mj,Sigma_mj,sigma_mj_2],[mu_mj,Sigma_mj,sigma_mj_2]]]

# only mode a

In [3]:
result_args_a = EM_iteration(train_dataset_mode_a,[1],100, 
                             0.1, *args_a)

  5%|████▍                                                                              | 3/56 [00:00<00:02, 21.35it/s]

iteration:1,loss:3.593435101860026


  4%|██▉                                                                                | 2/56 [00:00<00:02, 19.11it/s]

iteration:2,loss:0.8234499981940331


  5%|████▍                                                                              | 3/56 [00:00<00:02, 23.15it/s]

iteration:3,loss:0.7261851965250324


  4%|██▉                                                                                | 2/56 [00:00<00:02, 19.87it/s]

iteration:4,loss:0.6094445893232683


  2%|█▍                                                                                 | 1/56 [00:00<00:06,  8.03it/s]

iteration:5,loss:0.5390319675114038


  5%|████▍                                                                              | 3/56 [00:00<00:02, 24.88it/s]

iteration:6,loss:0.4944800097258229


  5%|████▍                                                                              | 3/56 [00:00<00:02, 24.67it/s]

iteration:7,loss:0.4710897729583987


  4%|██▉                                                                                | 2/56 [00:00<00:03, 16.58it/s]

iteration:8,loss:0.4407272439799341


  5%|████▍                                                                              | 3/56 [00:00<00:02, 26.18it/s]

iteration:9,loss:0.40042191508982417


  5%|████▍                                                                              | 3/56 [00:00<00:02, 22.80it/s]

iteration:10,loss:0.35589757653092846


  4%|██▉                                                                                | 2/56 [00:00<00:03, 17.15it/s]

iteration:11,loss:0.31096405349065726


  2%|█▍                                                                                 | 1/56 [00:00<00:07,  7.84it/s]

iteration:12,loss:0.2676400547785935


  5%|████▍                                                                              | 3/56 [00:00<00:02, 25.08it/s]

iteration:13,loss:0.22762173295939953


  5%|████▍                                                                              | 3/56 [00:00<00:02, 24.27it/s]

iteration:14,loss:0.1922720199443499


  5%|████▍                                                                              | 3/56 [00:00<00:02, 25.47it/s]

iteration:15,loss:0.16224646785150265


  5%|████▍                                                                              | 3/56 [00:00<00:02, 22.29it/s]

iteration:16,loss:0.1374702374880811


  5%|████▍                                                                              | 3/56 [00:00<00:02, 24.88it/s]

iteration:17,loss:0.11737775962542356


  5%|████▍                                                                              | 3/56 [00:00<00:02, 24.67it/s]

iteration:18,loss:0.10118916883188304


100%|██████████████████████████████████████████████████████████████████████████████████| 56/56 [00:02<00:00, 24.52it/s]

Done! iteration:19,loss:0.08811156221933103


In [4]:
RUL_a_hat = get_RUL(test_dataset_mode_a,[1],*result_args_a)
RUL_a_hat

100%|██████████████████████████████████████████████████████████████████████████████████| 55/55 [00:10<00:00,  5.17it/s]


array([ 52, 112, 114,  54,  62,  54,  86,  85, 107, 104,  37,  93,  59,
         8, 140, 127, 160,  84,  85,  81, 226, 155,  26, 124,  66, 101,
       128,  76,  17,  87, 158,  80, 137,  58, 128, 108,  41,  52, 135,
       132, 128, 156,  78,  96,  17,  24, 188,  75,  39,  88, 151,  68,
       116, 135,  38])

In [5]:
RUL_a = RUL[index_a]
RUL_a

array([ 51, 120,  99,  71,  55,  55,  66,  77, 115, 115,  31,  85,  58,
        11, 144, 124,  79,  55,  71,  65, 137, 145,  22, 115,  69, 111,
       137,  55,  11,  78, 120,  87,  87,  55,  93,  88,  40,  49, 128,
       115,  87, 100,  63,  99,  27,  18, 145, 104,  25,  68, 144,  51,
        81, 123,  17], dtype=int64)

In [14]:
sum(abs(RUL_a-RUL_a_hat))

941

# only mode b

In [17]:
result_args_b = EM_iteration(train_dataset_mode_b,[1],100, 0.1, *args_b)

  0%|                                                                                           | 0/44 [00:00<?, ?it/s]

iteration:1,loss:1.567121711656494


  0%|                                                                                           | 0/44 [00:00<?, ?it/s]

iteration:2,loss:0.5740135968196443


  0%|                                                                                           | 0/44 [00:00<?, ?it/s]

iteration:3,loss:0.7740629981244349


  5%|███▊                                                                               | 2/44 [00:00<00:02, 16.31it/s]

iteration:4,loss:0.7021885642589217


  5%|███▊                                                                               | 2/44 [00:00<00:02, 15.93it/s]

iteration:5,loss:1.0772980111675285


  0%|                                                                                           | 0/44 [00:00<?, ?it/s]

iteration:6,loss:2.134288905892464


  0%|                                                                                           | 0/44 [00:00<?, ?it/s]

iteration:7,loss:1.6547782838231575


  5%|███▊                                                                               | 2/44 [00:00<00:02, 14.86it/s]

iteration:8,loss:0.793140159020356


  5%|███▊                                                                               | 2/44 [00:00<00:02, 16.67it/s]

iteration:9,loss:0.7180225345551362


  2%|█▉                                                                                 | 1/44 [00:00<00:05,  7.60it/s]

iteration:10,loss:0.8752512640560715


  0%|                                                                                           | 0/44 [00:00<?, ?it/s]

iteration:11,loss:0.9910637181267118


  5%|███▊                                                                               | 2/44 [00:00<00:02, 16.86it/s]

iteration:12,loss:0.8023933519745702


  5%|███▊                                                                               | 2/44 [00:00<00:02, 14.98it/s]

iteration:13,loss:0.5360391321126807


  5%|███▊                                                                               | 2/44 [00:00<00:02, 16.52it/s]

iteration:14,loss:0.41090249203937634


  5%|███▊                                                                               | 2/44 [00:00<00:03, 13.74it/s]

iteration:15,loss:0.38412982785142635


  5%|███▊                                                                               | 2/44 [00:00<00:02, 19.11it/s]

iteration:16,loss:0.3640700462817204


  0%|                                                                                           | 0/44 [00:00<?, ?it/s]

iteration:17,loss:0.3271705727924036


  5%|███▊                                                                               | 2/44 [00:00<00:02, 19.30it/s]

iteration:18,loss:0.27692190682418855


  5%|███▊                                                                               | 2/44 [00:00<00:02, 19.11it/s]

iteration:19,loss:0.22456792393814715


  5%|███▊                                                                               | 2/44 [00:00<00:02, 19.11it/s]

iteration:20,loss:0.18163623632649767


  0%|                                                                                           | 0/44 [00:00<?, ?it/s]

iteration:21,loss:0.1548642065782164


  0%|                                                                                           | 0/44 [00:00<?, ?it/s]

iteration:22,loss:0.1427094969918241


  5%|███▊                                                                               | 2/44 [00:00<00:02, 18.41it/s]

iteration:23,loss:0.1373983523607351


  5%|███▊                                                                               | 2/44 [00:00<00:02, 16.86it/s]

iteration:24,loss:0.13225691418608695


  5%|███▊                                                                               | 2/44 [00:00<00:02, 17.73it/s]

iteration:25,loss:0.12461251677251377


  0%|                                                                                           | 0/44 [00:00<?, ?it/s]

iteration:26,loss:0.11461150790499089


  0%|                                                                                           | 0/44 [00:00<?, ?it/s]

iteration:27,loss:0.10375944491661766


100%|██████████████████████████████████████████████████████████████████████████████████| 44/44 [00:02<00:00, 18.63it/s]

Done! iteration:28,loss:0.09385887645053285


In [18]:
RUL_b_hat = get_RUL(test_dataset_mode_b,[1],*result_args_b)
RUL_b_hat

100%|██████████████████████████████████████████████████████████████████████████████████| 45/45 [00:09<00:00,  4.64it/s]


array([ 52,  47, 224, 116,  72, 318, 165,  74,  30, 146, 122,  16, 143,
        79, 115,   1,  56, 143, 176,   8, 409, 192,  60, 155,  28, 118,
       225,  48,  56, 177,  44, 105,  27, 334,  21,   8,  79,  63,  22,
        80,  13, 175, 169,  11,  23])

In [19]:
RUL_b = RUL[index_b]
RUL_b

array([ 44,  27, 101, 108,  56, 136, 132,  56,  18, 119,  78,   9,  88,
        89,  87,   8,  41, 131, 128,   7, 135, 129,  58, 117,  28,  92,
       103,  35,  45, 117,  45,  86,  20, 133,  15,   6,  56,  41,  14,
        67,  10, 127, 113,   8,  28], dtype=int64)

In [20]:
sum(abs(RUL_b-RUL_b_hat))

1700

# all

In [21]:
args_all = result_args_a+result_args_b

In [22]:
result_args = EM_iteration(train_dataset,[1,1],100, 0.1, *args_all)

100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:11<00:00,  8.86it/s]


iteration:1,loss:0.7201752499608823


100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:18<00:00,  5.37it/s]


iteration:2,loss:0.16342917053910486


100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:09<00:00, 10.41it/s]


iteration:3,loss:0.15527866582780536


100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:08<00:00, 12.06it/s]


iteration:4,loss:0.15035857300134525


100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:08<00:00, 11.88it/s]

Done! iteration:5,loss:0.1461025541314197


In [23]:
result_args

[[0.56,
  array([[ 0.13824405],
         [ 0.09684941],
         [ 0.17773055],
         [ 0.0428787 ],
         [ 0.2664821 ],
         [-0.03235442]]),
  [array([[ 0.79527427],
          [-0.40687373],
          [ 5.9546097 ]]),
   array([[ 0.14072198, -0.04634148, -0.34757783],
          [-0.04634148,  0.07798319,  0.06798981],
          [-0.34757783,  0.06798981,  4.63797647]]),
   0.06562153538852418],
  [array([[ 0.82183615],
          [-0.39026626],
          [ 5.41444036]]),
   array([[ 0.11442283,  0.03056187, -0.55331843],
          [ 0.03056187,  0.14006109, -0.42258319],
          [-0.55331843, -0.42258319,  5.89324521]]),
   0.06466388682409162],
  [array([[ 0.58417815],
          [-0.36526356],
          [ 7.05539944]]),
   array([[ 0.11753175, -0.05601834, -0.38618258],
          [-0.05601834,  0.15717115, -0.30155292],
          [-0.38618258, -0.30155292,  7.6652503 ]]),
   0.04461100175860337],
  [array([[-0.46745876],
          [ 0.36217601],
          [-7.72814833]])

In [24]:
np.save('./numpy/arg_all_result041201.npy',np.array(result_args,dtype=object))

In [25]:
np.save('./numpy/arg_all_result041201_a.npy',np.array(result_args_a,dtype=object))
np.save('./numpy/arg_all_result041201_b.npy',np.array(result_args_b,dtype=object))