In [1]:
from EM_part import*

In [3]:
train_dataset_mode_a =  AircraftDataset_one_mode(df_train,train_label,-1)
train_dataset_mode_b =  AircraftDataset_one_mode(df_train,train_label,1)

In [4]:
#initial
set_seed(612)
w_k=np.random.rand(6,1)
pi_k=np.random.random(size=None)
mu_mk=np.random.rand(3,1)
Sigma_mk=generate_rand_psd(3)
sigma_mk_2=np.random.random(size=None)

w_j=np.random.rand(6,1)
pi_j=np.random.random(size=None)
mu_mj=np.random.rand(3,1)
Sigma_mj=generate_rand_psd(3)
sigma_mj_2=np.random.random(size=None)

args_a = [[pi_k,w_k,[mu_mk,Sigma_mk,sigma_mk_2],
                               [mu_mk,Sigma_mk,sigma_mk_2],[mu_mk,Sigma_mk,sigma_mk_2],[mu_mk,Sigma_mk,sigma_mk_2],
                              [mu_mk,Sigma_mk,sigma_mk_2],[mu_mk,Sigma_mk,sigma_mk_2],[mu_mk,Sigma_mk,sigma_mk_2]]]
args_b = [[pi_k,w_k,[mu_mj,Sigma_mj,sigma_mj_2],
                               [mu_mj,Sigma_mj,sigma_mj_2],[mu_mj,Sigma_mj,sigma_mj_2],[mu_mj,Sigma_mj,sigma_mj_2],
                              [mu_mj,Sigma_mj,sigma_mj_2],[mu_mj,Sigma_mj,sigma_mj_2],[mu_mj,Sigma_mj,sigma_mj_2]]]


args = [[pi_k,w_k,[mu_mk,Sigma_mk,sigma_mk_2],
                               [mu_mk,Sigma_mk,sigma_mk_2],[mu_mk,Sigma_mk,sigma_mk_2],[mu_mk,Sigma_mk,sigma_mk_2],
                              [mu_mk,Sigma_mk,sigma_mk_2],[mu_mk,Sigma_mk,sigma_mk_2],[mu_mk,Sigma_mk,sigma_mk_2]],
                                 [pi_k,w_k,[mu_mj,Sigma_mj,sigma_mj_2],
                               [mu_mj,Sigma_mj,sigma_mj_2],[mu_mj,Sigma_mj,sigma_mj_2],[mu_mj,Sigma_mj,sigma_mj_2],
                              [mu_mj,Sigma_mj,sigma_mj_2],[mu_mj,Sigma_mj,sigma_mj_2],[mu_mj,Sigma_mj,sigma_mj_2]]]

In [15]:
def EM_iteration(instance, Dk_list, iteration, limitation, *args):
    epoch = 1
    while epoch < iteration:
        # get old para
        pi_list, w_list, mu_list, Sigma_list, sigma_2_list = pack_para(*args)
        # update w
        w_list_new = get_new_w(train_dataset, Dk_list, *args)
        args_new_w = repack_para(pi_list, w_list_new, mu_list, Sigma_list, sigma_2_list)
        # update other
        pi_list_new, mu_list_new, Sigma_list_new, sigma_2_list_new = get_new_para(train_dataset, *args_new_w)
        # pi_list_new = get_hat_pi_k(train_dataset,*args_new_w)
        args_new_all = repack_para(pi_list_new, w_list_new, mu_list_new, Sigma_list_new, sigma_2_list_new)
        loss = rmse(mu_list, mu_list_new) + rmse(Sigma_list, Sigma_list_new) + rmse(sigma_2_list, sigma_2_list_new) + \
               rmse(pi_list, pi_list_new) + rmse(w_list, w_list_new)
        args = args_new_all
        if loss > limitation:
            print(f"iteration:{epoch},loss:{loss}")
            epoch += 1
            continue
        else:
            print(f"Done! iteration:{epoch},loss:{loss}")
            return args
            break
        

In [37]:
result_args_a = EM_iteration(train_dataset_mode_a,[-10],100, 0.125, *args_a)

  0%|                                                                                          | 0/100 [00:00<?, ?it/s]

iteration:1,loss:8.14678574414988


  0%|                                                                                          | 0/100 [00:00<?, ?it/s]

iteration:2,loss:9.02244059507375


  0%|                                                                                          | 0/100 [00:00<?, ?it/s]

iteration:3,loss:7.324054591737753


  0%|                                                                                          | 0/100 [00:00<?, ?it/s]

iteration:4,loss:6.607488992385326


  0%|                                                                                          | 0/100 [00:00<?, ?it/s]

iteration:5,loss:11.64991322564272


  0%|                                                                                          | 0/100 [00:00<?, ?it/s]

iteration:6,loss:22.574278830835155


  0%|                                                                                          | 0/100 [00:00<?, ?it/s]

iteration:7,loss:20.48794764070402


  0%|                                                                                          | 0/100 [00:00<?, ?it/s]

iteration:8,loss:8.636853350601655


  0%|                                                                                          | 0/100 [00:00<?, ?it/s]

iteration:9,loss:2.514492696715747


  0%|                                                                                          | 0/100 [00:00<?, ?it/s]

iteration:10,loss:0.6816395305376322


  0%|                                                                                          | 0/100 [00:00<?, ?it/s]

iteration:11,loss:0.21767650473693184


100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:07<00:00, 14.09it/s]

Done! iteration:12,loss:0.11196449856665718


In [17]:
print(result_args_a)

[[1.0, array([[-0.14045283],
       [-0.0761299 ],
       [-0.175566  ],
       [-0.03195801],
       [-0.2850372 ],
       [ 0.02610236]]), [array([[ 0.76085534],
       [-0.64258793],
       [ 5.14331935]]), array([[ 0.10117771, -0.03086741, -0.23799786],
       [-0.03086741,  0.27726715,  0.01783484],
       [-0.23799786,  0.01783484,  5.24168217]]), 0.07434942316519406], [array([[ 0.75447506],
       [-0.6039017 ],
       [ 5.01699731]]), array([[ 0.09404274,  0.04545429, -0.37210914],
       [ 0.04545429,  0.20815525, -0.33635538],
       [-0.37210914, -0.33635538,  5.88373777]]), 0.07880722913445141], [array([[ 0.51772171],
       [-0.93745906],
       [ 6.91015764]]), array([[ 0.09692472, -0.02644149, -0.27295452],
       [-0.02644149,  0.8671843 , -1.32923874],
       [-0.27295452, -1.32923874, 11.76414252]]), 0.06063212219471496], [array([[-0.31790217],
       [-0.21394242],
       [-1.16794057]]), array([[ 0.11737109, -0.20591658,  1.02724263],
       [-0.20591658,  0.9853919

In [38]:
result_args_b = EM_iteration(train_dataset_mode_b,[10],100, 0.125, *args_b)

  0%|                                                                                          | 0/100 [00:00<?, ?it/s]

iteration:1,loss:6.473841730675868


  0%|                                                                                          | 0/100 [00:00<?, ?it/s]

iteration:2,loss:5.283442416979277


  0%|                                                                                          | 0/100 [00:00<?, ?it/s]

iteration:3,loss:4.2887099022711945


  0%|                                                                                          | 0/100 [00:00<?, ?it/s]

iteration:4,loss:0.4461231736138522


100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:09<00:00, 10.06it/s]

Done! iteration:5,loss:0.023651222910325873


In [19]:
result_args_b

[[1.0,
  array([[ 0.15545951],
         [ 0.0853063 ],
         [ 0.21510783],
         [ 0.09778131],
         [ 0.30734505],
         [-0.06254572]]),
  [array([[0.60809568],
          [1.11980674],
          [1.28939103]]),
   array([[ 0.10907698, -0.05458853, -0.13484672],
          [-0.05458853,  0.14563002,  0.31791727],
          [-0.13484672,  0.31791727,  0.6975289 ]]),
   0.08046172987184734],
  [array([[0.60729606],
          [1.10812711],
          [1.26400419]]),
   array([[ 0.11626067, -0.05689385, -0.14135053],
          [-0.05689385,  0.11340877,  0.25021752],
          [-0.14135053,  0.25021752,  0.55563499]]),
   0.08422504408055881],
  [array([[0.31876037],
          [1.36642505],
          [1.86569468]]),
   array([[ 0.11096142, -0.06036969, -0.14768302],
          [-0.06036969,  0.21637338,  0.4681108 ],
          [-0.14768302,  0.4681108 ,  1.01656566]]),
   0.07038765156488647],
  [array([[-0.37162515],
          [ 0.01989047],
          [-0.89608724]]),
   array

In [21]:
args_all = result_args_a+result_args_b

In [39]:
result_args = EM_iteration(train_dataset,[-10,10],100, 0.2, *args_all)

100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:23<00:00,  4.21it/s]


iteration:1,loss:44.044727855281245


100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:23<00:00,  4.21it/s]


iteration:2,loss:6.937172268411775


100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:20<00:00,  4.85it/s]


iteration:3,loss:1.3050210683286756


100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:15<00:00,  6.37it/s]


iteration:4,loss:1.817906874140491


100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:12<00:00,  7.74it/s]


iteration:5,loss:2.3695883694832562


100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:18<00:00,  5.55it/s]


iteration:6,loss:3.6468821561235134


100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:12<00:00,  7.82it/s]


iteration:7,loss:2.2436816025953057


100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:12<00:00,  7.71it/s]


iteration:8,loss:2.4865206037044914


100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:20<00:00,  4.95it/s]


iteration:9,loss:2.237312840253631


100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:17<00:00,  5.70it/s]


iteration:10,loss:2.310282079433653


100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:13<00:00,  7.63it/s]


iteration:11,loss:2.233633546396382


100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:19<00:00,  5.26it/s]


iteration:12,loss:2.261801817695055


100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:11<00:00,  8.48it/s]


iteration:13,loss:2.2322416153548126


 35%|████████████████████████████▎                                                    | 35/100 [00:05<00:10,  6.21it/s]


KeyboardInterrupt: 

In [40]:
result_args

[[0.56,
  array([[-0.14107795],
         [-0.07269193],
         [-0.1833172 ],
         [-0.0283842 ],
         [-0.28645507],
         [ 0.01634209]]),
  [array([[ 0.80116542],
          [-0.49698436],
          [ 6.19754031]]),
   array([[ 0.13931929, -0.03756375, -0.36207992],
          [-0.03756375,  0.14939987, -0.28534003],
          [-0.36207992, -0.28534003,  6.09838779]]),
   0.0655713138859101],
  [array([[ 0.82468967],
          [-0.42851781],
          [ 5.50735066]]),
   array([[ 0.11349203,  0.03677791, -0.56846498],
          [ 0.03677791,  0.16090321, -0.50379678],
          [-0.56846498, -0.50379678,  6.20848893]]),
   0.0646515251422192],
  [array([[ 0.58496356],
          [-0.37879269],
          [ 7.09347277]]),
   array([[ 0.11858449, -0.06840603, -0.35377243],
          [-0.06840603,  0.2823017 , -0.6051624 ],
          [-0.35377243, -0.6051624 ,  8.35371785]]),
   0.04456603529665039],
  [array([[-0.46930976],
          [ 0.39135126],
          [-7.80706822]]),


In [30]:
np.array(result_args,dtype=object).tolist()

[[0.56,
  array([[-0.14107795],
         [-0.07269193],
         [-0.1833172 ],
         [-0.0283842 ],
         [-0.28645507],
         [ 0.01634209]]),
  [array([[ 0.80116542],
          [-0.49698436],
          [ 6.19754031]]),
   array([[ 0.13931929, -0.03756375, -0.36207992],
          [-0.03756375,  0.14939987, -0.28534003],
          [-0.36207992, -0.28534003,  6.09838779]]),
   0.0655713138859101],
  [array([[ 0.82468967],
          [-0.42851781],
          [ 5.50735066]]),
   array([[ 0.11349203,  0.03677791, -0.56846498],
          [ 0.03677791,  0.16090321, -0.50379678],
          [-0.56846498, -0.50379678,  6.20848893]]),
   0.0646515251422192],
  [array([[ 0.58496356],
          [-0.37879269],
          [ 7.09347277]]),
   array([[ 0.11858449, -0.06840603, -0.35377243],
          [-0.06840603,  0.2823017 , -0.6051624 ],
          [-0.35377243, -0.6051624 ,  8.35371785]]),
   0.04456603529665039],
  [array([[-0.46930976],
          [ 0.39135126],
          [-7.80706822]]),


In [ ]:
np.save('./numpy/arg_all_result040702.npy',np.array(result_args,dtype=object))

In [32]:
arg = np.load('./numpy/arg_all_result0407.npy',allow_pickle=True).tolist()